version: "27.0.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/sports_app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:3000"
    stdin_open: true

  mongo:
    image: mongo:5
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
